scheduling/urls.py
# scheduling/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.schedule_view, name='schedule'),  # Отображение расписания
    path('calculate/', views.calculate_schedule_view, name='calculate_schedule'),  # Расчет расписания
    path('students/',views.students_view, name='students_view'),
    path("students/edit/<int:id>/", views.edit_student),
    path("students/delete/<int:id>/", views.delete_student),
    path('subjects/', views.subject_view, name='subject_view'),
    path("subjects/edit/<int:id>/", views.edit_subject),
    path("students/delete/<int:id>/", views.delete_subject),
    path('teachers/', views.teacher_view, name='teacher_view'),
    path("teachers/edit/<int:id>/", views.edit_teacher),
    path("teachers/delete/<int:id>/", views.delete_teacher),
    path('time_slots/', views.time_slots_view),
    path("time_slots/edit/<int:id>/", views.edit_time_slot),
    path("time_slots/delete/<int:id>/", views.delete_time_slot),
    path('get-teachers/', views.get_teachers, name='get_teachers'),
]

timetable_week/urls.py
# timetable_week/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduling.urls')),  # Включение маршрутов из приложения scheduling
]

scheduling/models.py
# templates/models.py

from django.db import models
class Subject(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name
class Teacher(models.Model):
    name = models.CharField(max_length=100)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=1)
    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher=models.ForeignKey(Teacher,on_delete=models.CASCADE)
    times_per_week=models.IntegerField(default=7)
    monday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    tuesday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    wednesday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    thursday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    friday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    saturday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)
    sunday_free_time = models.CharField(max_length=100, default="", null = True, blank = True)

    def __str__(self):
        return self.name

class TimeSlot(models.Model):
    start_time = models.CharField(max_length=20)
    end_time = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.start_time} - {self.end_time}"

class Availability(models.Model):
    DAYS_OF_WEEK = (
        (0, 'Понедельник'),
        (1, 'Вторник'),
        (2, 'Среда'),
        (3, 'Четверг'),
        (4, 'Пятница'),
        (5, 'Суббота'),
        (6, 'Воскресенье'),
    )

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE,default=1)
    time_slot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)
    day_of_week = models.IntegerField(choices=DAYS_OF_WEEK)
    subject= models.ForeignKey(Subject, on_delete=models.CASCADE, default=1)
    available = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.student} - {self.get_day_of_week_display()} - {self.time_slot} - {'Available' if self.available else 'Not Available'}"

class Lesson(models.Model):
    DAYS_OF_WEEK = (
        (0, 'Понедельник'),
        (1, 'Вторник'),
        (2, 'Среда'),
        (3, 'Четверг'),
        (4, 'Пятница'),
        (5, 'Суббота'),
        (6, 'Воскресенье'),
    )

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    day_of_week = models.IntegerField(choices=DAYS_OF_WEEK)
    time_slot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student} - {self.subject} - {self.teacher} - {self.get_day_of_week_display()} - {self.time_slot}"

scheduling/forms.py
# templates/forms.py

from django import forms
from .models import *

# class AvailabilityForm(forms.ModelForm):
#     student = forms.ModelChoiceField(queryset=Student.objects.all())
#     time_slot = forms.ModelChoiceField(queryset=TimeSlot.objects.all())
#     day_of_week = forms.ChoiceField(choices=Availability.DAYS_OF_WEEK)
#     available = forms.BooleanField(required=False)
#
#     class Meta:
#         model = Availability
#         fields = ['student', 'time_slot', 'day_of_week', 'available']

class StudentForm(forms.ModelForm):
    subject = forms.ModelChoiceField(queryset=Subject.objects.all())
    teacher=forms.ModelChoiceField(queryset=Teacher.objects.all())
    class Meta:
        model= Student
        fields='__all__'
        labels = {'name': 'Имя',
                  'subject':'Тип коробки передач',
                  'teacher':'Инструктор',
                  'times_per_week':'Желаемое количество занятий в неделю',
                  'monday_free_time':"Свободное время в понедельник",
                  'tuesday_free_time':"Свободное время во вторник",
                  'wednesday_free_time':"Свободное время в среду",
                  'thursday_free_time':"Свободное время в четверг",
                  'friday_free_time':"Свободное время в пятницу",
                  'saturday_free_time':"Свободное время в субботу",
                  'sunday_free_time':"Свободное время в воскресенье"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['teacher'].queryset = Teacher.objects.none()

        if 'subject' in self.data:
            try:
                subject_id = int(self.data.get('subject'))
                self.fields['teacher'].queryset = Teacher.objects.filter(subject_id=subject_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Teacher queryset
        elif self.instance.pk:
            self.fields['teacher'].queryset = self.instance.subject.teacher_set.order_by('name')
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields=['name']
        labels={'name':'Тип трансмиссии'}
class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields=['name','subject']
        labels={'name':'Имя инструктора','subject':'Трансмиссия на учёбной машине'}
class TimeSlotForm(forms.ModelForm):
    class Meta:
        model = TimeSlot
        fields = ['start_time','end_time']
        labels={'start_time':'Время начала занятия','end_time':'Время конца занятия'}

scheduling/views.py
from django.shortcuts import render

# Create your views here.
# templates/views.py

from django.shortcuts import render, redirect
from .models import *
from .forms import *
from .optimization import calculate_schedule
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.http import JsonResponse
def get_teachers(request):
    subject_id = request.GET.get('subject_id')
    teachers = Teacher.objects.filter(subject_id=subject_id).values('id', 'name')
    return JsonResponse(list(teachers), safe=False)
def calculate_schedule_view(request):
    if request.method == 'POST':
        status = calculate_schedule()
        if status:
            return redirect('schedule')
        else:
            return render(request, 'error.html', {'message': 'Unable to calculate schedule.'})
    return render(request, 'calculate_schedule.html')

def schedule_view(request):
    # Получаем все уроки
    lessons = Lesson.objects.all()

    # Создаем словарь, где ключами будут дни недели, а значениями - соответствующие уроки
    schedule = {i: [] for i in range(7)}
    for lesson in lessons:
        schedule[lesson.day_of_week].append(lesson)

    # Сортируем уроки по времени начала внутри каждого дня
    for day in schedule:
        schedule[day].sort(key=lambda x: x.time_slot.start_time)

    context = {'schedule': schedule}
    return render(request, 'schedule.html', context)


def students_view(request):
    if request.method=='POST':
        form=StudentForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            name=data.get('name')
            teacher = data.get('teacher')
            subject = data.get('subject')
            times_per_week=data.get('times_per_week')
            monday_free_time=data.get('monday_free_time')
            tuesday_free_time = data.get('tuesday_free_time')
            wednesday_free_time = data.get('wednesday_free_time')
            thursday_free_time = data.get('thursday_free_time')
            friday_free_time = data.get('friday_free_time')
            saturday_free_time = data.get('saturday_free_time')
            sunday_free_time = data.get('sunday_free_time')
            Student.objects.create(name=name, teacher=teacher, subject=subject, times_per_week=times_per_week, \
                                   monday_free_time= monday_free_time, tuesday_free_time=tuesday_free_time,  \
                                   wednesday_free_time = wednesday_free_time , thursday_free_time=thursday_free_time, \
                                   friday_free_time= friday_free_time,saturday_free_time=saturday_free_time, \
                                    sunday_free_time=sunday_free_time)
        students=Student.objects.all()
        return render(request,'enter_students.html',{'form':form,'students':students})

    form=StudentForm()
    students = Student.objects.all()
    return render(request, 'enter_students.html', {'form': form, 'students': students})


# изменение данных в бд
def edit_student(request, id):
    try:
        student = Student.objects.get(id=id)

        if request.method == "POST":
            form = StudentForm(request.POST, instance=student)
            if form.is_valid():
                form.save()
                return redirect("/students")
        else:
            form = StudentForm(instance=student)
            students = Student.objects.all()
            return render(request, "enter_students.html", {'form': form, 'students': students})
    except Student.DoesNotExist:
        return HttpResponseNotFound("<h2>Курсант не найден</h2>")


# удаление данных из бд
def delete_student(request, id):
    try:
        student = Student.objects.get(id=id)
        student.delete()
        return redirect("/students")
    except Student.DoesNotExist:
        return HttpResponseNotFound("<h2>Курсант не найден</h2>")
#==================================================================================
#Добавление, изменение и удаление предметов
def subject_view(request):
    if request.method=='POST':
        form=SubjectForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            name=data.get('name')
            Subject.objects.create(name=name)
            subjects=Subject.objects.all()
        form=SubjectForm()
        return render(request,'enter_subjects.html',{'form':form,'subjects':subjects})
    form=SubjectForm()
    subjects = Subject.objects.all()
    return render(request, 'enter_subjects.html', {'form': form, 'subjects': subjects})


# изменение данных в бд
def edit_subject(request, id):
    try:
        subject = Subject.objects.get(id=id)

        if request.method == "POST":
            form=SubjectForm(request.POST)
            if form.is_valid():
                data=form.cleaned_data
                subject.name = data.get("name")
                subject.save()
            return redirect("/subjects")
        else:
            form = StudentForm()
            subjects = Subject.objects.all()
            return render(request, "enter_subjects.html",{'form':form,'subjects':subjects})
    except Subject.DoesNotExist:
        return HttpResponseNotFound("<h2>Трансмиссия не найдена</h2>")

# удаление данных из бд
def delete_subject(request, id):
    try:
        subject = Subject.objects.get(id=id)
        subject.delete()
        return redirect("/subjects")
    except Subject.DoesNotExist:
        return HttpResponseNotFound("<h2>Трансмиссия не найдена</h2>")
#==================================================================================
#Добавление, изменение и удаление инструкторов
def teacher_view(request):
    if request.method=='POST':
        form=TeacherForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            name=data.get('name')
            subject=data.get('subject')
            Teacher.objects.create(name=name,subject=subject)
            teachers=Teacher.objects.all()
        form=TeacherForm()
        return render(request,'enter_teachers.html',{'form':form,'teachers':teachers})
    form=TeacherForm()
    teachers = Teacher.objects.all()
    return render(request, 'enter_teachers.html', {'form': form, 'teachers': teachers})


# изменение данных в бд
def edit_teacher(request, id):
    try:
        teacher = Teacher.objects.get(id=id)

        if request.method == "POST":
            form=TeacherForm(request.POST)
            if form.is_valid():
                data=form.cleaned_data
                teacher.name = data.get("name")
                teacher.subject=data.get('subject')
                teacher.save()
            return redirect("/teachers")
        else:
            form = TeacherForm()
            teachers = Teacher.objects.all()
            return render(request, "enter_teachers.html",{'form':form,'teachers':teachers})
    except Teacher.DoesNotExist:
        return HttpResponseNotFound("<h2>Инструктор не найден</h2>")

# удаление данных из бд
def delete_teacher(request, id):
    try:
       teacher = Teacher.objects.get(id=id)
       teacher.delete()
       return redirect("/teachers")
    except Teacher.DoesNotExist:
        return HttpResponseNotFound("<h2>Инструктор не найден</h2>")
#добавление временных отрезков (по умолчаению генерируются автоматически в optimization.py) Здесь только посмотреть на них
def time_slots_view(request):
    if request.method == 'POST':
        form = TimeSlotForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            time = data.get('time')
            TimeSlot.objects.create(time=time)
            time_slots = TimeSlot.objects.all()
        return render(request, 'enter_time_slots.html', {'form': form, 'time_slots': time_slots})
    form = TimeSlotForm()
    time_slots = TimeSlot.objects.all()
    return render(request, 'enter_time_slots.html', {'form': form, 'time_slots': time_slots})
def edit_time_slot(request, id):
    try:
        time_slot = TimeSlot.objects.get(id=id)
        if request.method == "POST":
            form=TimeSlotForm(request.POST)
            if form.is_valid():
                data=form.cleaned_data
                time_slot.time = data.get("time")
                time_slot.save()
            return redirect("/time_slots")
        else:
            form = TimeSlotForm()
            time_slots = TimeSlot.objects.all()
            return render(request, "enter_time_slots.html",{'form':form,'time_slots':time_slots})
    except TimeSlot.DoesNotExist:
        return HttpResponseNotFound("<h2>Временной отрезок не найден</h2>")

# удаление данных из бд
def delete_time_slot(request, id):
    try:
        time_slot = TimeSlot.objects.get(id=id)
        time_slot.delete()
        return redirect("/time_slots")
    except Student.DoesNotExist:
        return HttpResponseNotFound("<h2>Временной отрезок не найден</h2>")

scheduling/templates/calculate_schedule.html
<!-- scheduling/templates/scheduling/calculate_schedule.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Расчет расписания</title>
</head>
<body>
    <h1>Расчет расписания</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Рассчитать расписание</button>
    </form>
</body>
</html>

scheduling/templates/enter_students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Курсанты</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<p><a href="/">На главную</a></p>
<p><a href="/time_slots">Часы вождения</a></p>
<h2>Введите имена курсантов на вождение</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
<hr>
<table>
    <tr>
        <th>Имя курсанта</th>
        <th>Имя инструктора</th>
        <th>Тип трансмиссии</th>
        <th>Занятий в неделю</th>
        <th>Понедельник</th>
        <th>Вторник</th>
        <th>Среда</th>
        <th>Четверг</th>
         <th>Пятница</th>
         <th>Суббота</th>
         <th>Воскресенье</th>
        <th></th>
          <th></th>
    </tr>
    {% for student in students %}
    <tr>
        <td>{{ student.name }}</td>
        <td>{{ student.teacher }}</td>
        <td>{{ student.subject }}</td>
        <td>{{student.times_per_week}}</td>
        <td>{{ student.monday_free_time }}</td>
         <td>{{ student.tuesday_free_time }}</td>
         <td>{{ student.wednesday_free_time }}</td>
         <td>{{ student.thursday_free_time }}</td>
         <td>{{ student.friday_free_time }}</td>
         <td>{{ student.saturday_free_time }}</td>
        <td>{{ student.sunday_free_time }}</td>
        <td><a href="edit/{{ student.id }}">Изменить</a></td>
        <td><a href="delete/{{ student.id }}">Удалить</a></td>
    </tr>
    {% endfor %}
</table>


<script type="text/javascript">
    $(document).ready(function () {
        $('#id_subject').change(function () {
            var url = "{% url 'get_teachers' %}";
            var subjectId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'subject_id': subjectId
                },
                success: function (data) {
                    var select = $('#id_teacher');
                    select.empty();

                    $.each(data, function (index, item) {
                        select.append($('<option></option>').attr('value', item.id).text(item.name));
                    });
                }
            });
        });
    });
</script>

</body>
</html>

scheduling/templates/enter_subjects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Трансмиссии</title>
</head>
<body>
    <p><a href="/">На главную</a></p>
    <p><a href="/time_slots">Часы вождения</a></p>
<h2>Введите типы трансмиссий</h2>
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
<hr>
<table>
    <tr>
        <th>Тип трансмиссии</th>
        <th></th>
        <th></th>

    </tr>
{% for subject in subjects %}
    <tr>
    <td>{{subject.name}}  </td>
        <td><a href="edit/{{student.id}}">Изменить</a> </td>
        <td><a href="delete/{{student.id}}">Удалить</a></td>
    </tr>
{%endfor%}
</table>

</body>
</html>

scheduling/templates/enter_teachers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Инструкторы</title>
</head>
<body>
    <p><a href="/">На главную</a></p>
    <p><a href="/time_slots">Часы вождения</a></p>
<h2>Введите имя инструктора</h2>
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
<hr>
<table>
    <tr>
        <th>Имя инструктора</th>
        <th>Вид трансмиссии на учёбной машине</th>
        <th></th>
        <th></th>

    </tr>
{% for teacher in teachers %}
    <tr>
        <td>{{teacher.name}}  </td>
        <td>{{teacher.subject}}  </td>
        <td><a href="edit/{{teacher.id}}">Изменить</a> </td>
        <td><a href="delete/{{teacher.id}}">Удалить</a></td>
    </tr>
{%endfor%}
</table>

</body>
</html>

scheduling/templates/enter_time_slots.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Введите часы аождения:</title>
</head>
<body>
   <p><a href="/">На главную</a></p>
    <p><a href="/time_slots">Часы вождения</a></p>
<h2>Введите часы аождения:</h2>
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
<hr>
<table>
    <tr>
        <th>Время начала</th>
        <th>Время конца</th>
        <th></th>
        <th></th>
    </tr>
{% for time_slot in time_slots %}
    <tr>
    <td>{{time_slot.start_time}}  </td>
        <td>{{time_slot.end_time}}  </td>
        <td><a href="edit/{{time_slot.id}}">Изменить</a> </td>
        <td><a href="delete/{{time_slot.id}}">Удалить</a></td>
    </tr>
{%endfor%}
</table>

</body>
</html>

scheduling/templates/error.html
<!-- scheduling/templates/scheduling/error.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Ошибка</title>
</head>
<body>
    <h1>Ошибка</h1>
    <p>{{ message }}</p>
</body>
</html>

scheduling/templates/schedule.html
<!DOCTYPE html>
<html>
<head>
    <title>Расписание занятий</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
 <div>
        <a href="calculate/">Рассчитать расписание</a><br>
        <a href="students/">Курсанты</a><br>
        <a href="teachers/">Инструкторы</a><br>
        <a href="subjects/">Виды трансмиссий</a><br>
        <a href="time_slots/">Время для занятий</a>
    </div>
    <h1>Расписание занятий</h1>
    {% for day, lessons in schedule.items %}
        <h2>{{ lessons.0.get_day_of_week_display }}</h2>
        <table>
            <thead>
                <tr>
                    <th>Студент</th>
                    <th>Предмет</th>
                    <th>Учитель</th>
                    <th>Время</th>
                </tr>
            </thead>
            <tbody>
                {% for lesson in lessons %}
                    <tr>
                        <td>{{ lesson.student.name }}</td>
                        <td>{{ lesson.subject.name }}</td>
                        <td>{{ lesson.teacher.name }}</td>
                        <td>{{ lesson.time_slot.start_time }} - {{ lesson.time_slot.end_time }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">Нет занятий</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

</body>
</html>